version: '2.4'
services:
  meshtasticd:
    build:
      context: ./meshtasticd
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    volumes:
      - meshtasticd_data:/root/.portduino/default/prefs
      - meshtastic_web:/usr/share/doc/meshtasticd/web
    restart: unless-stopped

volumes:
  meshtasticd_data:
  meshtastic_web: