version: '2.4'
services:
  meshtasticd:
    build:
      context: ./meshtasticd
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    volumes:
      - meshtasticd_data:/root/.portduino/default/prefs
    restart: unless-stopped
  web:
    image: ghcr.io/meshtastic/web
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    ports:
      - "8080:8080"
    restart: always
volumes:
  meshtasticd_data:

